push to google drive on stop

diff --git a/timelapse b/timelapse
--- a/timelapse
+++ b/timelapse
@@ -1,10 +1,17 @@
 #!/bin/bash
 
-: ${PHOTOBASE:=$HOME/photos}
-: ${TIMELAPSE:=600000}
+if [ -z "$PHOTOBASE" ]; then
+	echo "missing PHOTOBASE setting" >&2
+	exit 1
+fi
+
+if [ -z "$INTERVAL" ]; then
+	echo "missing INTERVAL setting" >&2
+	exit 1
+fi
 
 TODAY=$(date +%Y-%m-%d)
 PHOTOS=$PHOTOBASE/$TODAY
 
 mkdir -p $PHOTOS
-/usr/bin/raspistill -o $PHOTOS/photo-%d.jpg -tl $TIMELAPSE
+/usr/bin/raspistill -o $PHOTOS/photo-%d.jpg -tl $INTERVAL
